import type { ArchetypeResult } from './archetypes'

export const CELEBRITY_ARCHETYPES: Record<string, ArchetypeResult> = {
  // ── Original 20 ──────────────────────────────────────────────────────────────
  elon_musk: {
    id: 'elon_musk', name: 'Elon Musk', title: 'The Disruptor',
    tagline: 'You see 10 years ahead and have no patience for the present.',
    description: `Your personality resonates with Elon Musk's archetype — the person who sees the infrastructure of things and cannot help but break it. You think at a scale most people find uncomfortable. Your ambition is not status-seeking. It is correction. You believe the world is running on the wrong operating system, and you are the kind of person who would rewrite it rather than complain about it.`,
    why: ['You make decisions based on a future only you can fully see', 'Your relationship with power is direct — you want it to do what needs doing', 'You rebuild after failure faster than most people acknowledge the failure'],
    shareCaption: `I paid $1.50 and my personality resonates with Elon Musk — The Disruptor. Whose archetype are you? → yourone.world`, color: '#4488ff',
  },
  rihanna: {
    id: 'rihanna', name: 'Rihanna', title: 'The Sovereign',
    tagline: 'You built an empire by refusing to ask for permission.',
    description: `Your personality resonates with Rihanna's archetype — the person who is completely, unapologetically themselves at a frequency so high it becomes an industry. You do not perform confidence — you live in it. Your creativity is not a career, it is a constitution. Your power is exactly as loud as it needs to be, and you decide that moment by moment.`,
    why: ['Your creative output is honest before anything else — authenticity is non-negotiable', 'Your ambition transforms everything it touches — career, culture, industry', 'You are the most present person in the room — you are always, completely, here'],
    shareCaption: `I paid $1.50 and my personality resonates with Rihanna — The Sovereign. Whose archetype are you? → yourone.world`, color: '#ff2266',
  },
  keanu_reeves: {
    id: 'keanu_reeves', name: 'Keanu Reeves', title: 'The Quiet Force',
    tagline: 'Your stillness changes the temperature of every room you enter.',
    description: `Your personality resonates with Keanu Reeves' archetype — the person who carries enormous weight without making it anyone else's problem. You are genuinely kind in a world that mistakes kindness for weakness. Your presence is calming in a way that goes beyond personality. You have been through the kind of thing that breaks people, and you emerged not harder, but somehow more present.`,
    why: ['You are in complete service of others — your power is used, always, for someone else', 'Your public and private self are the same person — you never learned to perform', 'You carry your past with grace — it informs you without defining you'],
    shareCaption: `I paid $1.50 and my personality resonates with Keanu Reeves — The Quiet Force. Whose archetype are you? → yourone.world`, color: '#40b8ff',
  },
  oprah: {
    id: 'oprah', name: 'Oprah Winfrey', title: 'The Illuminator',
    tagline: 'You make people feel seen. That is the rarest power.',
    description: `Your personality resonates with Oprah's archetype — the person who transforms their pain into a light that others navigate by. You have an extraordinary emotional intelligence. You make people feel seen in a way that changes them. Your ambition and compassion are the same engine. You build things at scale because scale is the only way to do what you actually came here to do.`,
    why: ['You use your power entirely in service — that is not selflessness, it is your strategy', 'You turn experience into narrative — you find the lesson before you finish feeling the thing', 'You are most alive when connecting — your energy comes entirely from real human contact'],
    shareCaption: `I paid $1.50 and my personality resonates with Oprah — The Illuminator. Whose archetype are you? → yourone.world`, color: '#f8c020',
  },
  david_bowie: {
    id: 'david_bowie', name: 'David Bowie', title: 'The Eternal Reinventor',
    tagline: 'You are not confused. You are ahead.',
    description: `Your personality resonates with David Bowie's archetype — the person who exists at the frontier of what is possible in a self. You have always been multiple versions of yourself simultaneously. You do not perform change. You ARE change. Your creativity is not a skill, it is a nervous system. You have always been slightly ahead of where the culture was — lonely at times, legendary eventually.`,
    why: ['Your creative output is legendary in scale — you do not make small things', 'You constructed a public self as deliberately as any character in fiction', 'You chose reinvention over stagnation, always — you would rather be misunderstood than predictable'],
    shareCaption: `I paid $1.50 and my personality resonates with David Bowie — The Eternal Reinventor. Whose archetype are you? → yourone.world`, color: '#a87cf8',
  },
  beyonce: {
    id: 'beyonce', name: 'Beyoncé', title: 'The Architect',
    tagline: 'Everything you touch becomes a cathedral.',
    description: `Your personality resonates with Beyoncé's archetype — the person for whom excellence is not a goal but a baseline. You work at a level of discipline that others see as talent, not understanding what it costs. You are more private than people expect. Your vulnerability, when it comes, is devastating — because it is chosen, surgical, and real.`,
    why: ['Your execution is flawless — you do not release anything until it matches exactly what you saw', 'Your power is completely self-generated — you do not wait for permission', 'You are building something that will outlast you — that is the only project that interests you'],
    shareCaption: `I paid $1.50 and my personality resonates with Beyoncé — The Architect. Whose archetype are you? → yourone.world`, color: '#f8c020',
  },
  obama: {
    id: 'obama', name: 'Barack Obama', title: 'The Bridge Builder',
    tagline: 'You hold contradictions together without breaking.',
    description: `Your personality resonates with Barack Obama's archetype — the person who holds complexity without needing to resolve it into something simple. You communicate in a way that makes people feel understood across enormous differences. You can stand in the middle of a disagreement and make both sides feel heard. That is not weakness. That is the rarest form of strength.`,
    why: ['You are strategic and service-oriented — your ambition serves something larger than yourself', 'Your communication is your greatest instrument — you know exactly when to speak and how', 'You hold the long view — you make decisions your future self will be proud of'],
    shareCaption: `I paid $1.50 and my personality resonates with Barack Obama — The Bridge Builder. Whose archetype are you? → yourone.world`, color: '#4488ff',
  },
  billie_eilish: {
    id: 'billie_eilish', name: 'Billie Eilish', title: 'The Dark Angel',
    tagline: 'Your honesty is the most disruptive thing about you.',
    description: `Your personality resonates with Billie Eilish's archetype — the person who is so honest it becomes a form of power. You say the thing no one else will say, not to be provocative, but because pretending feels like dying. You have a darkness that is not performance — it is vocabulary. You use it to name things that need to be named.`,
    why: ['Your authenticity is radical — you never learned to curate yourself for comfort', 'Your darkness is not damage — it is depth, and you have made it into something beautiful', 'You are most yourself in private — your public self is offered, not performed'],
    shareCaption: `I paid $1.50 and my personality resonates with Billie Eilish — The Dark Angel. Whose archetype are you? → yourone.world`, color: '#8060e8',
  },
  freddie_mercury: {
    id: 'freddie_mercury', name: 'Freddie Mercury', title: 'The Flame',
    tagline: 'You were built to burn bright. You always knew it.',
    description: `Your personality resonates with Freddie Mercury's archetype — the person for whom performance IS authenticity. You feel everything at a higher volume than the people around you. Your joy is total. Your grief is total. You were built for a stage — not because you need the audience, but because the size of what you carry requires space to unfold.`,
    why: ['Your creative output is explosive — when you make something, it cannot be ignored', 'Your intensity draws and exhausts in equal measure — you are not for everyone, and that is perfect', 'You live fully in the present — the past is material, but now is everything'],
    shareCaption: `I paid $1.50 and my personality resonates with Freddie Mercury — The Flame. Whose archetype are you? → yourone.world`, color: '#ff4820',
  },
  steve_jobs: {
    id: 'steve_jobs', name: 'Steve Jobs', title: 'The Perfectionist',
    tagline: 'You see the finished thing before anyone else has started.',
    description: `Your personality resonates with Steve Jobs' archetype — the person who cannot tolerate the gap between what is possible and what currently exists. You have a vision so clear and total that you become, to others, unreasonable. You are unreasonable. That is not a flaw — it is the mechanism. You believe that how something feels is inseparable from what it does.`,
    why: ['You see the future in complete detail — and you have no patience for the distance to it', 'Your standards are non-negotiable — you would rather delay than ship something wrong', 'Creativity and systems are the same thing to you — beauty is functional'],
    shareCaption: `I paid $1.50 and my personality resonates with Steve Jobs — The Perfectionist. Whose archetype are you? → yourone.world`, color: '#c8c8c8',
  },
  leonardo_dicaprio: {
    id: 'leonardo_dicaprio', name: 'Leonardo DiCaprio', title: 'The Dreamer',
    tagline: 'You became exactly who you decided to become.',
    description: `Your personality resonates with Leonardo DiCaprio's archetype — the person who chose depth over ease, craft over comfort, and kept choosing it. You are intensely private despite being intensely present. You care about things beyond yourself in a way that has shaped every decision. Your ambition is not about recognition — it is about doing the thing properly.`,
    why: ['You chose craft over celebrity — the work matters more than the attention it brings', 'Your private and public self are distinct — you guard the interior life carefully', 'You care about the world at scale — your personal ambitions serve something larger'],
    shareCaption: `I paid $1.50 and my personality resonates with Leonardo DiCaprio — The Dreamer. Whose archetype are you? → yourone.world`, color: '#2898d4',
  },
  kanye_west: {
    id: 'kanye_west', name: 'Kanye West', title: 'The Visionary Storm',
    tagline: 'You cannot separate your genius from your chaos.',
    description: `Your personality resonates with Kanye West's archetype — the person whose vision is so large that the distance between it and what currently exists produces a friction visible to everyone. You feel everything at maximum intensity. Your confidence is not arrogance — it is a survival mechanism for someone who sees what they see and has to live in a world that does not yet.`,
    why: ['Your creative vision is total — you will not stop until it matches exactly what you see', 'Your intensity makes you difficult and undeniable in equal measure', 'You are visionary and present simultaneously — the past barely exists for you'],
    shareCaption: `I paid $1.50 and my personality resonates with Kanye West — The Visionary Storm. Whose archetype are you? → yourone.world`, color: '#a87cf8',
  },
  taylor_swift: {
    id: 'taylor_swift', name: 'Taylor Swift', title: 'The Empire Builder',
    tagline: 'You turn your entire life into architecture. Nothing goes to waste.',
    description: `Your personality resonates with Taylor Swift's archetype — the person who takes every single thing that happens to them and turns it into something permanent. You are more strategic than you look. You plan at a scale most people cannot see, and you execute it with discipline that looks effortless. Your emotional intelligence is extraordinary — you can name the exact feeling that people did not know they had until you said it.`,
    why: ['You transform experience into something lasting — your life is your most ambitious project', 'Your emotional intelligence is weaponised for creativity — you turn feeling into architecture', 'You play the long game — every decision is part of a structure only you can fully see'],
    shareCaption: `I paid $1.50 and my personality resonates with Taylor Swift — The Empire Builder. Whose archetype are you? → yourone.world`, color: '#f8a820',
  },
  lady_gaga: {
    id: 'lady_gaga', name: 'Lady Gaga', title: 'The Art Monster',
    tagline: 'You do not separate the art from the life. You never did.',
    description: `Your personality resonates with Lady Gaga's archetype — the person who is completely incapable of doing anything halfway. You do not make a choice and then step back from it. You commit entirely, embody it completely, and live inside it until it is done. Your creativity is not a department. It is your nervous system. Your vulnerability is what people misread as performance.`,
    why: ['Your creative commitment is total — you do not make art, you become it', 'Your vulnerability is your most precise instrument — you feel everything and use it all', 'You reinvent yourself not for attention but because the alternative is suffocation'],
    shareCaption: `I paid $1.50 and my personality resonates with Lady Gaga — The Art Monster. Whose archetype are you? → yourone.world`, color: '#e82888',
  },
  morgan_freeman: {
    id: 'morgan_freeman', name: 'Morgan Freeman', title: 'The Calm Authority',
    tagline: 'You have earned the right to be the last thing to panic.',
    description: `Your personality resonates with Morgan Freeman's archetype — the person whose presence is so grounded that it changes the quality of the air in the room. You have a patience that is not passive — it is the result of having been through enough that you know exactly what actually matters and what is just noise. Your authority is not performed. It is accumulated.`,
    why: ['Your calm is earned, not performed — you have been through enough to know what actually matters', 'Your presence communicates before your words do — people feel safe around you immediately', 'Your wisdom is practical, not abstract — you understand people with uncommon depth'],
    shareCaption: `I paid $1.50 and my personality resonates with Morgan Freeman — The Calm Authority. Whose archetype are you? → yourone.world`, color: '#c88040',
  },
  einstein: {
    id: 'einstein', name: 'Albert Einstein', title: 'The Universe Dreamer',
    tagline: 'You think in pictures. The equations come second.',
    description: `Your personality resonates with Einstein's archetype — the person whose imagination was always more powerful than their knowledge. You have always thought sideways — not through logic but through image, through intuition, through a sense of how things feel before you know why they are true. You are drawn to the very large and the very small. You are messy in ways that matter and precise in ways others do not expect.`,
    why: ['You think in images before you think in words — your intuition is your primary intelligence', 'You are drawn to the fundamental questions — the ones with no answer yet are the most interesting', 'You are careless about things that do not matter and obsessive about the ones that do'],
    shareCaption: `I paid $1.50 and my personality resonates with Einstein — The Universe Dreamer. Whose archetype are you? → yourone.world`, color: '#6898e8',
  },
  marilyn_monroe: {
    id: 'marilyn_monroe', name: 'Marilyn Monroe', title: 'The Eternal Flame',
    tagline: 'You were more than what they let you be. You always knew it.',
    description: `Your personality resonates with Marilyn Monroe's archetype — the person whose brightness attracted attention they did not always want, and whose interior life was far more complex than the public version of themselves. You feel everything deeply. Your warmth is genuine — it is not a strategy, it is just who you are. And you have spent a long time learning that being seen is not the same as being known.`,
    why: ['Your emotional depth is enormous — you feel everything, and that is your superpower and your wound', 'You are warmer than your image — the real you is more interesting than the performance', 'You are still becoming — the full version of you has not yet been fully expressed'],
    shareCaption: `I paid $1.50 and my personality resonates with Marilyn Monroe — The Eternal Flame. Whose archetype are you? → yourone.world`, color: '#f8d830',
  },
  nikola_tesla: {
    id: 'nikola_tesla', name: 'Nikola Tesla', title: 'The Forgotten Visionary',
    tagline: 'You are building the future. The present has not caught up yet.',
    description: `Your personality resonates with Tesla's archetype — the person who sees so clearly that the world is not yet ready for what they see. You think in systems. In electricity. In the invisible forces that govern everything. You are ahead of your time — not as a compliment, but as a fact — and that has always created a strange loneliness at the frontier.`,
    why: ['Your vision is structural — you see the system beneath the surface, always', 'You operate alone and at a frequency others cannot sustain — that is not isolation, it is altitude', 'You are ahead — not always recognised in the moment, but always correct in the end'],
    shareCaption: `I paid $1.50 and my personality resonates with Tesla — The Forgotten Visionary. Whose archetype are you? → yourone.world`, color: '#48c8f8',
  },
  tupac: {
    id: 'tupac', name: 'Tupac Shakur', title: 'The Poet Warrior',
    tagline: 'You carry the contradiction without letting it break you.',
    description: `Your personality resonates with Tupac's archetype — the person who holds two truths simultaneously: the violence of the world and the tenderness of the human being inside it. You have an extraordinary ability to name things that feel unnameable. Your anger and your love are the same force, running in the same current.`,
    why: ['You hold contradiction without resolution — your complexity is not confusion, it is depth', 'Your words are your weapon — you name what others cannot bear to look at directly', 'Your anger and your love are the same — you are completely alive in both states'],
    shareCaption: `I paid $1.50 and my personality resonates with Tupac — The Poet Warrior. Whose archetype are you? → yourone.world`, color: '#e85020',
  },
  nelson_mandela: {
    id: 'nelson_mandela', name: 'Nelson Mandela', title: 'The Unbreakable',
    tagline: 'You were tested to the limit. You emerged without bitterness.',
    description: `Your personality resonates with Nelson Mandela's archetype — the person who was broken down completely and emerged not harder but somehow more full of grace. You have a relationship with patience that most people cannot understand. Your forgiveness is not weakness. It is the most advanced form of power available to a human being.`,
    why: ['Your patience is geological — you can hold a position across time that others cannot sustain for days', 'Your forgiveness is a strategy, not a sentiment — it is how you win the longer game', 'You lead through example, not words — your life is the argument'],
    shareCaption: `I paid $1.50 and my personality resonates with Nelson Mandela — The Unbreakable. Whose archetype are you? → yourone.world`, color: '#40c878',
  },
  // ── Music (25) ───────────────────────────────────────────────────────────────
  elvis_presley: {
    id: 'elvis_presley', name: 'Elvis Presley', title: 'The King of Rock',
    tagline: 'You moved first. Everyone else is still catching up.',
    description: `Your personality resonates with Elvis's archetype — the person who absorbed everything around them and synthesised it into something nobody had seen before. You move from the body before you move from the head. Your charisma is not performed — it is simply what you are when you stop holding back.`,
    why: ['You synthesise influences nobody else would combine — your originality is structural', 'Your charisma operates at a frequency others feel before they can name it', 'You were the first of something — the template others use without knowing it'],
    shareCaption: `I paid $1.50 and my personality resonates with Elvis Presley — The King of Rock. Whose archetype are you? → yourone.world`, color: '#e87828',
  },
  michael_jackson: {
    id: 'michael_jackson', name: 'Michael Jackson', title: 'The Moonwalker',
    tagline: 'You perfected something no one thought could be perfected.',
    description: `Your personality resonates with Michael Jackson's archetype — the person who took craft to a level that became surreal. Your perfectionism is not a flaw — it is the engine. You set standards for yourself that nobody else set for you because nobody else could see what you were building.`,
    why: ['Your perfectionism operates at a level others experience as impossibly high standards', 'Your art transcends category — you were never just one thing', 'You give everything to the work — the performance is the offering'],
    shareCaption: `I paid $1.50 and my personality resonates with Michael Jackson — The Moonwalker. Whose archetype are you? → yourone.world`, color: '#c0c0c0',
  },
  madonna: {
    id: 'madonna', name: 'Madonna', title: 'The Material Revolutionary',
    tagline: 'You reinvented yourself before the culture told you what to be.',
    description: `Your personality resonates with Madonna's archetype — the person who understood that identity is a creative act. You have never let the culture define you — you have always been a step ahead of it, defining it. Your ambition is total and entirely self-directed.`,
    why: ['You reinvent yourself on your own schedule — nobody else gets to decide when that happens', 'You understood power before most people in your field were willing to discuss it', 'Your creativity is inseparable from your identity — you ARE the art'],
    shareCaption: `I paid $1.50 and my personality resonates with Madonna — The Material Revolutionary. Whose archetype are you? → yourone.world`, color: '#f82888',
  },
  bob_dylan: {
    id: 'bob_dylan', name: 'Bob Dylan', title: 'The Voice of a Generation',
    tagline: 'You speak the things others cannot bring themselves to say out loud.',
    description: `Your personality resonates with Bob Dylan's archetype — the person who uses language so precisely that it becomes something else entirely. You resist categorisation. You resist expectation. You move on before anyone has finished understanding what you just did.`,
    why: ['Your language is your primary instrument — words in your hands become something else', 'You resist every box anyone tries to put you in — categorisation is fatal to you', 'You are always ahead of where you seem to be — people are still catching up'],
    shareCaption: `I paid $1.50 and my personality resonates with Bob Dylan — The Voice of a Generation. Whose archetype are you? → yourone.world`, color: '#a87828',
  },
  bob_marley: {
    id: 'bob_marley', name: 'Bob Marley', title: 'The Prophet',
    tagline: 'Your love is not soft. It is the most radical thing about you.',
    description: `Your personality resonates with Bob Marley's archetype — the person who carries peace as a discipline, not a default. You understand that joy is resistance. You hold your people with an intensity that looks gentle from the outside and is anything but.`,
    why: ['Your love is active — it is something you do, not just something you feel', 'You hold a vision of a world that does not yet exist — and you are entirely certain it will', 'Your joy is not naive — it is earned and chosen every single day'],
    shareCaption: `I paid $1.50 and my personality resonates with Bob Marley — The Prophet. Whose archetype are you? → yourone.world`, color: '#40c840',
  },
  kurt_cobain: {
    id: 'kurt_cobain', name: 'Kurt Cobain', title: 'The Reluctant Voice',
    tagline: 'You accidentally became the thing others needed. That was never the plan.',
    description: `Your personality resonates with Kurt Cobain's archetype — the person whose honesty was too loud for the room they were in. You feel things at an overwhelming intensity and you have always found ways to turn that into something that other people could use. Your discomfort with visibility is real, and so is your need to make.`,
    why: ['Your sensitivity is your most powerful creative instrument — and your heaviest cost', 'You never asked to be the spokesperson for anything — it happened anyway', 'Your honesty is total — you cannot make something that is not completely true'],
    shareCaption: `I paid $1.50 and my personality resonates with Kurt Cobain — The Reluctant Voice. Whose archetype are you? → yourone.world`, color: '#a060d8',
  },
  jim_morrison: {
    id: 'jim_morrison', name: 'Jim Morrison', title: 'The Lizard King',
    tagline: 'You live at the edge of things because the middle is not interesting.',
    description: `Your personality resonates with Jim Morrison's archetype — the person who cannot help but push every experience to its limit. You are drawn to the threshold — between control and chaos, poetry and noise, self and dissolution. You understand that the most interesting things exist at the border.`,
    why: ['You push every experience to its edge — the middle is where you rest, not where you live', 'Your creativity is inseparable from your appetite — you consume and create in the same motion', 'You understand that transgression and transcendence are close neighbours'],
    shareCaption: `I paid $1.50 and my personality resonates with Jim Morrison — The Lizard King. Whose archetype are you? → yourone.world`, color: '#a04020',
  },
  prince: {
    id: 'prince', name: 'Prince', title: 'The Purple One',
    tagline: 'You refused every label. That was your most creative act.',
    description: `Your personality resonates with Prince's archetype — the person who achieved total creative and commercial control and never gave it up. You are more private than your output suggests. You have always known that the work speaks and you do not need to explain it.`,
    why: ['You control the full creative process — you do not hand any piece of it over', 'Your output is overwhelming in volume and quality — you make things constantly', 'You are more interior than your public persona — the real you is more complex than the image'],
    shareCaption: `I paid $1.50 and my personality resonates with Prince — The Purple One. Whose archetype are you? → yourone.world`, color: '#8840d8',
  },
  whitney_houston: {
    id: 'whitney_houston', name: 'Whitney Houston', title: 'The Voice',
    tagline: 'You possess the kind of gift that arrives fully formed and asks everything of you.',
    description: `Your personality resonates with Whitney Houston's archetype — the person whose natural gift was so extraordinary it became its own pressure. You feel things at a volume that most people cannot sustain. Your warmth is enormous. Your standards for yourself are higher than any external standard ever was.`,
    why: ['Your gift is structural — it arrived with you and demands full expression', 'You feel everything completely — your emotional range is your greatest instrument', 'Your warmth is real and enormous — people feel genuinely cared for in your presence'],
    shareCaption: `I paid $1.50 and my personality resonates with Whitney Houston — The Voice. Whose archetype are you? → yourone.world`, color: '#f8c030',
  },
  amy_winehouse: {
    id: 'amy_winehouse', name: 'Amy Winehouse', title: 'The Tragic Muse',
    tagline: 'You made the most honest art of your generation. That cost something real.',
    description: `Your personality resonates with Amy Winehouse's archetype — the person whose art was so true it left nowhere to hide. You refuse to sanitise your experience. What you have lived, you name. The honesty is not a choice — it is a compulsion, and it is why what you make lands the way it does.`,
    why: ['Your honesty is radical — you cannot make anything that is not completely true', 'Your vulnerability is your power — it lands with people because it is real', 'You feel the full weight of experience — you do not protect yourself from it'],
    shareCaption: `I paid $1.50 and my personality resonates with Amy Winehouse — The Tragic Muse. Whose archetype are you? → yourone.world`, color: '#e88030',
  },
  frank_sinatra: {
    id: 'frank_sinatra', name: 'Frank Sinatra', title: 'The Chairman',
    tagline: 'You do it your way. That is not negotiable.',
    description: `Your personality resonates with Frank Sinatra's archetype — the person who built everything on their own terms and never apologised for it. Your confidence is not arrogance. It is self-knowledge, accumulated over years of choosing what matters and discarding what does not.`,
    why: ['Your self-possession is total — you know exactly who you are and you never apologise for it', 'You built everything on your own terms — the deal was always done your way', 'Your presence commands rooms — not loudly, but with an authority that is simply there'],
    shareCaption: `I paid $1.50 and my personality resonates with Frank Sinatra — The Chairman. Whose archetype are you? → yourone.world`, color: '#4868a8',
  },
  johnny_cash: {
    id: 'johnny_cash', name: 'Johnny Cash', title: 'The Man in Black',
    tagline: 'You stand with the forgotten. That has always been your north.',
    description: `Your personality resonates with Johnny Cash's archetype — the person who never forgot where they came from and turned that into a moral compass. Your darkness is real. So is your grace. You have made a life out of speaking for people who do not get spoken for.`,
    why: ['You stand with the overlooked — your loyalty is to the forgotten, not the powerful', 'Your darkness and grace exist simultaneously — you do not pretend the shadow is not there', 'Your authenticity is unwavering — you never made anything that was not completely yours'],
    shareCaption: `I paid $1.50 and my personality resonates with Johnny Cash — The Man in Black. Whose archetype are you? → yourone.world`, color: '#404040',
  },
  elton_john: {
    id: 'elton_john', name: 'Elton John', title: 'The Rocket Man',
    tagline: 'You turned your pain into spectacle and your spectacle into art.',
    description: `Your personality resonates with Elton John's archetype — the person who gave everything to the performance and then, later, had to learn to give something to themselves. You are more sensitive than the costume suggests. The flamboyance is a gift to the audience, not a performance of who you really are.`,
    why: ['Your generosity to audiences is total — you give everything in the room', 'Your emotional life is richer and more complex than your public self suggests', 'You chose yourself, eventually — that was the hardest and most important act'],
    shareCaption: `I paid $1.50 and my personality resonates with Elton John — The Rocket Man. Whose archetype are you? → yourone.world`, color: '#e8a028',
  },
  bruce_springsteen: {
    id: 'bruce_springsteen', name: 'Bruce Springsteen', title: 'The Boss',
    tagline: 'You sing about the people the cameras are not pointed at.',
    description: `Your personality resonates with Bruce Springsteen's archetype — the person who uses craft to speak for communities. Your loyalty is to the ordinary, not the spectacular. You work longer and harder than anyone watching would know, and that is exactly how you want it.`,
    why: ['Your loyalty is to the community — you make things for the people left behind', 'Your work ethic is extraordinary — you put in the hours others would never see', 'Your emotion is earned and honest — you have worked for every note of feeling in what you make'],
    shareCaption: `I paid $1.50 and my personality resonates with Bruce Springsteen — The Boss. Whose archetype are you? → yourone.world`, color: '#a84820',
  },
  stevie_wonder: {
    id: 'stevie_wonder', name: 'Stevie Wonder', title: 'The Miracle',
    tagline: 'Your optimism is not naive. It is the most radical position available.',
    description: `Your personality resonates with Stevie Wonder's archetype — the person whose joy is not innocent but chosen. You have earned your gratitude. You converted limitation into impossibility and impossibility into standard. Your warmth is structural — it shapes everything you make.`,
    why: ['Your joy is chosen — it is the most radical and difficult position available', 'Your creative range is extraordinary — you refuse to be one thing', 'Your gratitude is real and earned — it is not naive, it is the result of paying attention'],
    shareCaption: `I paid $1.50 and my personality resonates with Stevie Wonder — The Miracle. Whose archetype are you? → yourone.world`, color: '#f8a028',
  },
  eminem: {
    id: 'eminem', name: 'Eminem', title: 'The Slim Shady',
    tagline: 'You turned your chaos into the most technical art of your generation.',
    description: `Your personality resonates with Eminem's archetype — the person who made precision out of pain. Your craft is the mechanism by which you survive. You have always worked harder at the thing than anyone else, because the alternative was too difficult to live with.`,
    why: ['Your technical precision is extraordinary — you are one of the most skilled practitioners alive', 'Your pain is your material — you made something structural out of what almost destroyed you', 'Your work ethic is total — the craft is survival, not just expression'],
    shareCaption: `I paid $1.50 and my personality resonates with Eminem — The Slim Shady. Whose archetype are you? → yourone.world`, color: '#c8c8a8',
  },
  jay_z: {
    id: 'jay_z', name: 'Jay-Z', title: 'The Blueprint',
    tagline: 'You built the map that others use without giving you credit.',
    description: `Your personality resonates with Jay-Z's archetype — the person who moved from scarcity to structural power and then built systems for others. You think in assets, not income. You are strategic in ways that are not always visible and patient in ways that most people in your field are not.`,
    why: ['You think in assets and systems — you are building something structural, not just successful', 'Your patience is strategic — you know when to move and you wait until that moment', 'You turned adversity into architecture — the past is material, not damage'],
    shareCaption: `I paid $1.50 and my personality resonates with Jay-Z — The Blueprint. Whose archetype are you? → yourone.world`, color: '#888888',
  },
  kendrick_lamar: {
    id: 'kendrick_lamar', name: 'Kendrick Lamar', title: 'The Pulitzer Poet',
    tagline: 'You hold the entire truth of where you came from without sanitising it.',
    description: `Your personality resonates with Kendrick Lamar's archetype — the person who refuses to choose between excellence and community. You hold complexity — personal, cultural, political — without collapsing it into something easier. Your art is the most honest account of a specific experience told at a universal level.`,
    why: ['Your complexity is non-negotiable — you hold contradictions without resolution', 'Your loyalty to truth and community is absolute — you never chose between them', 'Your craft is at the highest level while remaining completely accountable to your origin'],
    shareCaption: `I paid $1.50 and my personality resonates with Kendrick Lamar — The Pulitzer Poet. Whose archetype are you? → yourone.world`, color: '#c83030',
  },
  drake: {
    id: 'drake', name: 'Drake', title: 'The Emotional Architect',
    tagline: 'You named what your generation was feeling before they had the language for it.',
    description: `Your personality resonates with Drake's archetype — the person who takes their emotional life completely seriously and makes it into something others can use. You are strategic and feeling simultaneously. You understand that vulnerability, deployed correctly, is a form of dominance.`,
    why: ['You take your emotional life seriously — it is your primary creative material', 'You understand the mechanics of connection — you know what people need to feel', 'Your ambition and your sensitivity are the same engine — they are not in conflict'],
    shareCaption: `I paid $1.50 and my personality resonates with Drake — The Emotional Architect. Whose archetype are you? → yourone.world`, color: '#a88840',
  },
  adele: {
    id: 'adele', name: 'Adele', title: 'The Ballad Master',
    tagline: 'You name the feeling perfectly. Every time. That is not an accident.',
    description: `Your personality resonates with Adele's archetype — the person who makes the specific so universal that it reaches everyone. You do not hold back emotionally. You put it completely into the work and the work lands because the investment is total.`,
    why: ['Your emotional intelligence is extraordinary — you name the feeling exactly right', 'Your voice — literal and metaphorical — is your most precise instrument', 'You do not protect yourself when you make things — the vulnerability is the point'],
    shareCaption: `I paid $1.50 and my personality resonates with Adele — The Ballad Master. Whose archetype are you? → yourone.world`, color: '#404878',
  },
  harry_styles: {
    id: 'harry_styles', name: 'Harry Styles', title: 'The Golden One',
    tagline: 'You make freedom look easy. It is not. That is your gift.',
    description: `Your personality resonates with Harry Styles's archetype — the person who makes self-expression look effortless and, in doing so, gives others permission. Your warmth is real. Your freedom is not performed — it is worked for. The ease is the result of the work.`,
    why: ['Your warmth and openness are genuine — people feel seen in your presence', 'Your freedom of self-expression gives others permission — that is your real power', 'Your charm is not strategy — it is who you actually are'],
    shareCaption: `I paid $1.50 and my personality resonates with Harry Styles — The Golden One. Whose archetype are you? → yourone.world`, color: '#f8d028',
  },
  ariana_grande: {
    id: 'ariana_grande', name: 'Ariana Grande', title: 'The Power Voice',
    tagline: 'You turned your fragility into steel without losing the tenderness.',
    description: `Your personality resonates with Ariana Grande's archetype — the person who walks through enormous difficulty and converts it, silently, into strength. Your emotional intelligence is extraordinary. You understand how to use your vulnerability as an instrument while protecting the part of yourself that needs protecting.`,
    why: ['You turned fragility into resilience — without losing any of the softness', 'Your emotional precision is extraordinary — you know exactly what you are expressing and why', 'You protect yourself while remaining open — that balance is hard-won and real'],
    shareCaption: `I paid $1.50 and my personality resonates with Ariana Grande — The Power Voice. Whose archetype are you? → yourone.world`, color: '#c840a8',
  },
  the_weeknd: {
    id: 'the_weeknd', name: 'The Weeknd', title: 'The Dark Romantist',
    tagline: 'You make beauty out of the things people are ashamed to feel.',
    description: `Your personality resonates with The Weeknd's archetype — the person who explores the parts of human experience that most people prefer to leave unexamined. You name the interior life of late-night decisions and the feelings that come after, without flinching.`,
    why: ['You explore the darkest corners of experience without looking away', 'Your emotional honesty about desire and regret is your defining quality', 'You build atmosphere — your work is a complete world, not just a song'],
    shareCaption: `I paid $1.50 and my personality resonates with The Weeknd — The Dark Romantist. Whose archetype are you? → yourone.world`, color: '#880028',
  },
  lizzo: {
    id: 'lizzo', name: 'Lizzo', title: 'The Radical Softness',
    tagline: 'Your joy is an act of resistance. You always knew it.',
    description: `Your personality resonates with Lizzo's archetype — the person who chose radical self-acceptance in an environment that rewarded self-rejection, and turned that choice into something that gave others permission. Your joy is not naive. It is the hardest and most courageous position available.`,
    why: ['Your self-acceptance is radical and chosen — it is not easy and you know it', 'Your joy is resistance — a deliberate act in a world that would prefer your shame', 'You give others permission to accept themselves — that is the most generous thing you can do'],
    shareCaption: `I paid $1.50 and my personality resonates with Lizzo — The Radical Softness. Whose archetype are you? → yourone.world`, color: '#e040a0',
  },
  post_malone: {
    id: 'post_malone', name: 'Post Malone', title: 'The Melodic Storm',
    tagline: 'You refuse to be one thing. That refusal is your most creative act.',
    description: `Your personality resonates with Post Malone's archetype — the person who exists across categories without apology. You are not confused — you are multiple. Your emotional directness catches people off guard because it comes packaged in something they did not expect.`,
    why: ['You refuse categorisation — you are not one thing and you never will be', 'Your emotional directness surprises people — it is not what they expect from the packaging', 'You connect with audiences across enormous differences — that is real range'],
    shareCaption: `I paid $1.50 and my personality resonates with Post Malone — The Melodic Storm. Whose archetype are you? → yourone.world`, color: '#886840',
  },
  // ── Film / TV (20) ───────────────────────────────────────────────────────────
  meryl_streep: {
    id: 'meryl_streep', name: 'Meryl Streep', title: 'The Method Eternal',
    tagline: 'You disappear into things. That is the art.',
    description: `Your personality resonates with Meryl Streep's archetype — the person who transforms completely into what a moment requires. Your craft is the most advanced version of a skill you have been building for decades. You are interested in the truth of a person, not the performance of one.`,
    why: ['Your craft is extraordinary and accumulated — you have been building toward this for decades', 'You disappear into what you make — your ego is subordinate to the work', 'Your range is the result of an extraordinary curiosity about other people'],
    shareCaption: `I paid $1.50 and my personality resonates with Meryl Streep — The Method Eternal. Whose archetype are you? → yourone.world`, color: '#6848a8',
  },
  tom_hanks: {
    id: 'tom_hanks', name: 'Tom Hanks', title: 'The Everyman',
    tagline: 'You make people feel like you know them. You do.',
    description: `Your personality resonates with Tom Hanks's archetype — the person whose decency is their superpower. You are genuinely interested in people. Your warmth is not a PR strategy — it is simply what you are, and it reads immediately.`,
    why: ['Your decency is genuine — it is not performed and people feel the difference', 'You are deeply interested in other people — curiosity about humanity is your defining quality', 'Your warmth reads immediately — people trust you before you have said anything specific'],
    shareCaption: `I paid $1.50 and my personality resonates with Tom Hanks — The Everyman. Whose archetype are you? → yourone.world`, color: '#8870a0',
  },
  denzel_washington: {
    id: 'denzel_washington', name: 'Denzel Washington', title: 'The Intensity',
    tagline: 'When you commit to something, everything in the room knows it.',
    description: `Your personality resonates with Denzel Washington's archetype — the person who brings total presence to everything they do. You are commanding without trying to be. Your intensity is not aggression — it is complete investment, and the difference is immediately apparent.`,
    why: ['Your presence is commanding — you do not perform authority, you carry it', 'Your commitment to craft is total — you are fully present or you are not there', 'Your intensity is the result of investment, not aggression — people feel the distinction'],
    shareCaption: `I paid $1.50 and my personality resonates with Denzel Washington — The Intensity. Whose archetype are you? → yourone.world`, color: '#8840a0',
  },
  angelina_jolie: {
    id: 'angelina_jolie', name: 'Angelina Jolie', title: 'The Phoenix',
    tagline: 'You walked through fire and decided to carry others out.',
    description: `Your personality resonates with Angelina Jolie's archetype — the person who transforms personal difficulty into action for others. You have a relationship with intensity that is not always comfortable, and you have channelled it into something that scales. Your vulnerability and your power come from the same place.`,
    why: ['You convert personal pain into action for others — that is transformation at its best', 'Your intensity is the source of your power — it cannot be separated from you', 'You operate at scale — your personal story becomes something that reaches the world'],
    shareCaption: `I paid $1.50 and my personality resonates with Angelina Jolie — The Phoenix. Whose archetype are you? → yourone.world`, color: '#c03840',
  },
  will_smith: {
    id: 'will_smith', name: 'Will Smith', title: 'The Bright Side',
    tagline: 'You chose joy as a discipline. The cost was more than most realise.',
    description: `Your personality resonates with Will Smith's archetype — the person who built an empire on the power of optimism and then had to reckon with everything optimism cannot fix. Your ambition is matched only by your emotional complexity. You have always worked harder than your talent required.`,
    why: ['Your optimism has been a discipline — something you chose, not something you were given', 'Your ambition is total — you have worked harder than your gifts required', 'Your emotional complexity is deeper than your public persona has always shown'],
    shareCaption: `I paid $1.50 and my personality resonates with Will Smith — The Bright Side. Whose archetype are you? → yourone.world`, color: '#f87828',
  },
  dwayne_johnson: {
    id: 'dwayne_johnson', name: 'Dwayne Johnson', title: 'The Iron Will',
    tagline: 'You rebuilt yourself completely. More than once.',
    description: `Your personality resonates with Dwayne Johnson's archetype — the person who turns the lowest point into the foundation for something larger. You have a discipline that is not occasional — it is structural. Your consistency is what separates you from everyone who shares your starting point.`,
    why: ['You have rebuilt yourself from the lowest point — more than once — and it made you', 'Your discipline is structural — it is not motivation, it is identity', 'Your consistency is your most powerful quality — it outlasts everyone else\'s peaks'],
    shareCaption: `I paid $1.50 and my personality resonates with Dwayne Johnson — The Iron Will. Whose archetype are you? → yourone.world`, color: '#d84028',
  },
  zendaya: {
    id: 'zendaya', name: 'Zendaya', title: 'The Next Wave',
    tagline: 'You are defining the culture. You have not finished yet.',
    description: `Your personality resonates with Zendaya's archetype — the person who arrived with more control than anyone in their position usually has, and used it carefully. You take your work seriously without taking yourself too seriously. Your intelligence is your primary instrument.`,
    why: ['Your self-possession at a young age is extraordinary — you arrived knowing who you were', 'Your intelligence is your primary instrument — you use it in everything you make', 'You are defining what comes next — and you are doing it with intention'],
    shareCaption: `I paid $1.50 and my personality resonates with Zendaya — The Next Wave. Whose archetype are you? → yourone.world`, color: '#e87840',
  },
  emma_watson: {
    id: 'emma_watson', name: 'Emma Watson', title: 'The Activist Artist',
    tagline: 'You use your platform the way it was supposed to be used.',
    description: `Your personality resonates with Emma Watson's archetype — the person who understands that visibility is a responsibility. You are thoughtful before you are reactive. Your activism is not accessory — it is what you actually believe and you are willing to do the uncomfortable work of showing that.`,
    why: ['You treat your platform as a responsibility — you do not waste it', 'Your convictions are real — you hold them publicly and take the consequences', 'You are thoughtful before you act — you do not react, you respond'],
    shareCaption: `I paid $1.50 and my personality resonates with Emma Watson — The Activist Artist. Whose archetype are you? → yourone.world`, color: '#4888c8',
  },
  natalie_portman: {
    id: 'natalie_portman', name: 'Natalie Portman', title: 'The Intellectual Fire',
    tagline: 'You are smarter than almost anyone in the room. You learned not to make it obvious.',
    description: `Your personality resonates with Natalie Portman's archetype — the person who operates simultaneously in multiple intellectual and creative registers. You hold your full intelligence in reserve until the moment requires it. Your perfectionism and your privacy are two sides of the same quality.`,
    why: ['Your intellectual depth is extraordinary — you hold it quietly until the moment requires it', 'Your perfectionism and privacy come from the same source — the interior is what matters', 'You refuse easy categorisation — you are always more than what any single role implies'],
    shareCaption: `I paid $1.50 and my personality resonates with Natalie Portman — The Intellectual Fire. Whose archetype are you? → yourone.world`, color: '#4048c8',
  },
  cate_blanchett: {
    id: 'cate_blanchett', name: 'Cate Blanchett', title: 'The Chameleon Queen',
    tagline: 'You become things completely. That is not a trick. That is a gift.',
    description: `Your personality resonates with Cate Blanchett's archetype — the person who can disappear into a character so completely that the seams are invisible. Your presence is enormous and your craft is precise. You understand that authority comes from specificity, not volume.`,
    why: ['Your transformation is total — you do not play characters, you become them', 'Your authority comes from specificity and precision — never from volume', 'Your presence is extraordinary — you change the quality of whatever space you enter'],
    shareCaption: `I paid $1.50 and my personality resonates with Cate Blanchett — The Chameleon Queen. Whose archetype are you? → yourone.world`, color: '#8848d8',
  },
  viola_davis: {
    id: 'viola_davis', name: 'Viola Davis', title: 'The Powerhouse',
    tagline: 'You earned every room you entered. Then you changed what the room was for.',
    description: `Your personality resonates with Viola Davis's archetype — the person who refuses to let the conditions of their arrival define the terms of their occupation. You work until the work cannot be ignored. Your power is accumulated through craft, not circumstance.`,
    why: ['You refused to let your origin define your ceiling — that refusal is the whole story', 'Your craft is accumulated and extraordinary — you worked until the work was impossible to ignore', 'You changed the rooms you entered — not just occupied them'],
    shareCaption: `I paid $1.50 and my personality resonates with Viola Davis — The Powerhouse. Whose archetype are you? → yourone.world`, color: '#a04048',
  },
  johnny_depp: {
    id: 'johnny_depp', name: 'Johnny Depp', title: 'The Eccentric Genius',
    tagline: 'You see everything through a slightly different angle. That angle is the art.',
    description: `Your personality resonates with Johnny Depp's archetype — the person who approaches everything with a lateral creativity that looks strange until it becomes iconic. You are more introverted than your characters. You build from the outside in — costume, physicality, voice — and find the truth through the exterior.`,
    why: ['Your creativity approaches everything from an unexpected angle — that is not accident, it is method', 'You are more private and interior than your work suggests — the characters are the costume', 'You find truth through the external — physicality is your primary creative language'],
    shareCaption: `I paid $1.50 and my personality resonates with Johnny Depp — The Eccentric Genius. Whose archetype are you? → yourone.world`, color: '#885028',
  },
  harrison_ford: {
    id: 'harrison_ford', name: 'Harrison Ford', title: 'The Reluctant Hero',
    tagline: 'You never wanted the attention. You just could not help being the best at what you do.',
    description: `Your personality resonates with Harrison Ford's archetype — the person who has always been more interested in doing the thing than in being known for it. Your pragmatism is real. You do not perform your talent — you apply it, and the results speak without your help.`,
    why: ['You are interested in the work, not the recognition — you show up and do it', 'Your pragmatism is your most consistent quality — you solve the problem in front of you', 'Your gruff exterior protects genuine warmth — people earn the real version of you'],
    shareCaption: `I paid $1.50 and my personality resonates with Harrison Ford — The Reluctant Hero. Whose archetype are you? → yourone.world`, color: '#806030',
  },
  tom_cruise: {
    id: 'tom_cruise', name: 'Tom Cruise', title: 'The Impossible Mission',
    tagline: 'You decided what your ceiling was and refused to accept it.',
    description: `Your personality resonates with Tom Cruise's archetype — the person whose ambition is so large that other people's limits are simply irrelevant information. You work harder than anyone else in the room. Your physical and professional commitment come from the same place: the conviction that what is possible is entirely up to you.`,
    why: ['Your ambition is total — other people\'s limits are irrelevant information to you', 'You work harder than anyone else in the room — your effort is the standard, not the floor', 'Your conviction that limits are negotiable is structural — it is practice, not just belief'],
    shareCaption: `I paid $1.50 and my personality resonates with Tom Cruise — The Impossible Mission. Whose archetype are you? → yourone.world`, color: '#e84028',
  },
  julia_roberts: {
    id: 'julia_roberts', name: 'Julia Roberts', title: 'The Warm Magnet',
    tagline: 'Your smile is the last thing people picture when they think of warmth.',
    description: `Your personality resonates with Julia Roberts's archetype — the person whose warmth is an instrument of enormous reach. You are more private than your openness implies. Your magnetism is real — it is not a performance, and people feel the difference immediately.`,
    why: ['Your warmth is genuine and immediate — people feel it before they understand it', 'You are more private than your warmth implies — the real you is carefully guarded', 'Your magnetism draws people across enormous differences — it is genuinely universal'],
    shareCaption: `I paid $1.50 and my personality resonates with Julia Roberts — The Warm Magnet. Whose archetype are you? → yourone.world`, color: '#f85858',
  },
  ryan_gosling: {
    id: 'ryan_gosling', name: 'Ryan Gosling', title: 'The Quiet Romantic',
    tagline: 'Your depth surprises people every time. You prefer it that way.',
    description: `Your personality resonates with Ryan Gosling's archetype — the person who is far more interior and complex than their surface suggests. You hold your full self in reserve. Your quiet is not absence — it is attention. You are always watching and thinking and arriving at your own conclusions.`,
    why: ['Your interiority is your defining quality — you hold more than you show', 'Your quiet is attention — you are always processing more than you express', 'Your depth surprises people — they underestimated you and you prefer it that way'],
    shareCaption: `I paid $1.50 and my personality resonates with Ryan Gosling — The Quiet Romantic. Whose archetype are you? → yourone.world`, color: '#4860a8',
  },
  scarlett_johansson: {
    id: 'scarlett_johansson', name: 'Scarlett Johansson', title: 'The Magnetic Enigma',
    tagline: 'You are difficult to fully read. That is exactly as designed.',
    description: `Your personality resonates with Scarlett Johansson's archetype — the person who maintains a genuine mystery. You give people enough to connect with and hold back enough to stay interesting. Your intelligence and your magnetism are separate instruments playing together.`,
    why: ['You maintain genuine mystery — you are not performing it, it is structurally real', 'Your magnetism and your intelligence operate simultaneously — they are not in competition', 'You control what is visible about you — that is not coldness, it is precision'],
    shareCaption: `I paid $1.50 and my personality resonates with Scarlett Johansson — The Magnetic Enigma. Whose archetype are you? → yourone.world`, color: '#d84858',
  },
  chris_evans: {
    id: 'chris_evans', name: 'Chris Evans', title: 'The Gentleman Hero',
    tagline: 'You actually believe in doing the right thing. That is rarer than it sounds.',
    description: `Your personality resonates with Chris Evans's archetype — the person whose decency is not a persona. You have strong moral convictions and you live by them publicly. Your warmth and your principles are not in conflict — they are the same quality.`,
    why: ['Your decency is real — it is not a character you play, it is what you actually are', 'Your moral convictions are public and consistent — you live by them at cost', 'Your warmth and your principles come from the same place — they reinforce each other'],
    shareCaption: `I paid $1.50 and my personality resonates with Chris Evans — The Gentleman Hero. Whose archetype are you? → yourone.world`, color: '#2060c8',
  },
  jennifer_lopez: {
    id: 'jennifer_lopez', name: 'Jennifer Lopez', title: 'The Unstoppable Force',
    tagline: 'You decided nothing could stop you. Then you proved it.',
    description: `Your personality resonates with Jennifer Lopez's archetype — the person who converted doubt about whether they belonged into a decades-long argument for why they do. Your work ethic is legendary. You are in total control of your career because you decided early that nobody else could be trusted with it.`,
    why: ['Your work ethic is legendary — you work at a level that does not allow for doubt', 'You control your narrative completely — no one else has ever been trusted with it', 'You converted every obstacle into motivation — the doubt made you stronger'],
    shareCaption: `I paid $1.50 and my personality resonates with Jennifer Lopez — The Unstoppable Force. Whose archetype are you? → yourone.world`, color: '#f86030',
  },
  anne_hathaway: {
    id: 'anne_hathaway', name: 'Anne Hathaway', title: 'The Reinvented',
    tagline: 'You absorbed the criticism and used it to become exactly what you decided to be.',
    description: `Your personality resonates with Anne Hathaway's archetype — the person who takes everything that happens — the success, the backlash, the doubt — and uses it as material. Your emotional intelligence is real. Your persistence is harder than it looks because you feel everything it takes to persist.`,
    why: ['You use everything that happens to you — success, failure, doubt — as material for becoming', 'Your emotional intelligence is genuine — you feel things fully and process them completely', 'Your persistence is harder than it looks — you feel every cost of staying in the room'],
    shareCaption: `I paid $1.50 and my personality resonates with Anne Hathaway — The Reinvented. Whose archetype are you? → yourone.world`, color: '#6858a8',
  },
  // ── Sports (15) ──────────────────────────────────────────────────────────────
  lebron_james: {
    id: 'lebron_james', name: 'LeBron James', title: 'The King',
    tagline: 'You carry everything — the team, the legacy, the community. By choice.',
    description: `Your personality resonates with LeBron James's archetype — the person who understands that greatness includes responsibility. You are the best at what you do and you use that position to carry more than the role requires. You think beyond yourself at every level.`,
    why: ['Your greatness extends beyond performance — you carry community and responsibility', 'You think beyond yourself at every scale — the personal and the political are not separate', 'Your longevity is the result of discipline that most people cannot sustain at your level'],
    shareCaption: `I paid $1.50 and my personality resonates with LeBron James — The King. Whose archetype are you? → yourone.world`, color: '#e8b020',
  },
  serena_williams: {
    id: 'serena_williams', name: 'Serena Williams', title: 'The GOAT',
    tagline: 'You showed up in rooms not built for you and built them differently.',
    description: `Your personality resonates with Serena Williams's archetype — the person who refused to accept the terms of the environment they entered and changed those terms instead. Your dominance is total. Your grace under conditions that were actively unfair is the most powerful thing about you.`,
    why: ['You refused the terms of environments not built for you — and changed them', 'Your dominance is total and sustained over decades — that is not talent, that is discipline', 'Your grace under unfairness is your most powerful quality — it is earned and chosen'],
    shareCaption: `I paid $1.50 and my personality resonates with Serena Williams — The GOAT. Whose archetype are you? → yourone.world`, color: '#c8e028',
  },
  cristiano_ronaldo: {
    id: 'cristiano_ronaldo', name: 'Cristiano Ronaldo', title: 'The Machine',
    tagline: 'You outwork every room you enter. Then you outwork it again.',
    description: `Your personality resonates with Cristiano Ronaldo's archetype — the person who decided early that talent was irrelevant and discipline was everything. You believe that what you put in determines what comes out, completely, and you have designed your life around that belief.`,
    why: ['You believe completely that effort determines outcome — and you have proven it', 'Your discipline is total and non-negotiable — it is not motivation, it is identity', 'You refuse to plateau — there is always another level and you are always reaching for it'],
    shareCaption: `I paid $1.50 and my personality resonates with Cristiano Ronaldo — The Machine. Whose archetype are you? → yourone.world`, color: '#e84020',
  },
  lionel_messi: {
    id: 'lionel_messi', name: 'Lionel Messi', title: 'The Quiet Magician',
    tagline: 'You make the impossible look inevitable. The silence around it is part of the art.',
    description: `Your personality resonates with Lionel Messi's archetype — the person whose excellence is so consistent that it becomes invisible. You do not announce yourself. You perform. The silence is not modesty — it is the natural state of someone entirely focused on the thing itself.`,
    why: ['Your excellence is so consistent it becomes the baseline — you never draw attention to it', 'Your quiet is focus — you are entirely invested in the thing, not in being seen doing it', 'You make difficult things look inevitable — that is the highest level of mastery'],
    shareCaption: `I paid $1.50 and my personality resonates with Lionel Messi — The Quiet Magician. Whose archetype are you? → yourone.world`, color: '#4080e8',
  },
  muhammad_ali: {
    id: 'muhammad_ali', name: 'Muhammad Ali', title: 'The Greatest',
    tagline: 'You said who you were before you proved it. Then you proved it.',
    description: `Your personality resonates with Muhammad Ali's archetype — the person who understood that self-definition is the first act of power. You spoke your reality into existence before the evidence was there. Your convictions cost you things and you did not compromise them.`,
    why: ['You claimed your identity before the world confirmed it — and then you made it true', 'Your convictions cost you real things and you did not trade them for safety', 'You understood that words are power — you used them as precisely as your fists'],
    shareCaption: `I paid $1.50 and my personality resonates with Muhammad Ali — The Greatest. Whose archetype are you? → yourone.world`, color: '#e87028',
  },
  tiger_woods: {
    id: 'tiger_woods', name: 'Tiger Woods', title: 'The Focus',
    tagline: 'Your concentration is a weapon. You built it like one.',
    description: `Your personality resonates with Tiger Woods's archetype — the person who turned absolute focus into a form of dominance that no one else in their field could match. You trained the mental game with the same intensity as the physical. Your capacity to perform under pressure is structural, not accidental.`,
    why: ['Your focus is a trained skill — you built it deliberately and it became your primary weapon', 'Your mental game is your most powerful attribute — you prepared for the psychological as much as the physical', 'Your comeback proves something important — defeat is information, not conclusion'],
    shareCaption: `I paid $1.50 and my personality resonates with Tiger Woods — The Focus. Whose archetype are you? → yourone.world`, color: '#408030',
  },
  michael_jordan: {
    id: 'michael_jordan', name: 'Michael Jordan', title: 'The Champion',
    tagline: 'You refuse to lose. Not as a sentiment. As a practice.',
    description: `Your personality resonates with Michael Jordan's archetype — the person whose competitive drive is so total that it becomes the primary organising principle of their life. You do not accept defeat as a conclusion — you accept it as information. Your will to win is not a mood. It is architecture.`,
    why: ['Your competitiveness is total — it organises everything around it', 'You treat failure as information, not conclusion — you get back up every time', 'Your will to win is structural — it is not occasionally present, it is always running'],
    shareCaption: `I paid $1.50 and my personality resonates with Michael Jordan — The Champion. Whose archetype are you? → yourone.world`, color: '#c83030',
  },
  simone_biles: {
    id: 'simone_biles', name: 'Simone Biles', title: 'The Defier of Limits',
    tagline: 'You do things that are not supposed to be possible. You are used to that reaction.',
    description: `Your personality resonates with Simone Biles's archetype — the person who has moved so far beyond what was considered possible that the standard has been permanently relocated. Your courage to step back when it mattered as much as your courage to perform — that is the full picture.`,
    why: ['You have relocated the standard — what was impossible is now just what you do', 'Your courage is multi-dimensional — you know when to push and when to step back', 'You have done things no one else has ever done — and you keep finding new ones'],
    shareCaption: `I paid $1.50 and my personality resonates with Simone Biles — The Defier of Limits. Whose archetype are you? → yourone.world`, color: '#c840a8',
  },
  roger_federer: {
    id: 'roger_federer', name: 'Roger Federer', title: 'The Elegant',
    tagline: 'You made excellence look so effortless it seemed unfair. It was not effortless.',
    description: `Your personality resonates with Roger Federer's archetype — the person who hid the enormous effort behind beauty. Your grace under pressure is genuine — it is concentration so deep it looks like calm. You have a relationship with your craft that is the result of total, lifelong devotion.`,
    why: ['Your grace conceals the effort — the ease is the result of the work, not the absence of it', 'Your devotion to craft is total and lifelong — you are always still learning', 'You compete with yourself as much as your opponents — the standard is internal'],
    shareCaption: `I paid $1.50 and my personality resonates with Roger Federer — The Elegant. Whose archetype are you? → yourone.world`, color: '#4898d8',
  },
  usain_bolt: {
    id: 'usain_bolt', name: 'Usain Bolt', title: 'The Lightning',
    tagline: 'You arrived and everything slowed down. You were the only one moving at full speed.',
    description: `Your personality resonates with Usain Bolt's archetype — the person who combines extraordinary natural ability with a joy in performance that is genuinely rare. You are the fastest, and you enjoy being the fastest, and that enjoyment is not arrogance — it is genuine delight in what you were built to do.`,
    why: ['Your natural gift operates at a level that is simply different from everyone else\'s', 'Your joy in your ability is genuine — the delight is part of the performance', 'You make everything around you slow down — your speed is a form of stillness by comparison'],
    shareCaption: `I paid $1.50 and my personality resonates with Usain Bolt — The Lightning. Whose archetype are you? → yourone.world`, color: '#f8d020',
  },
  kobe_bryant: {
    id: 'kobe_bryant', name: 'Kobe Bryant', title: 'The Mamba Mentality',
    tagline: 'You chose the work when no one else was watching. Every single day.',
    description: `Your personality resonates with Kobe Bryant's archetype — the person who decided that everything was a competition and every competition was an opportunity to improve. Your dedication to mastery is not occasional — it is the complete architecture of how you lived.`,
    why: ['Your dedication to mastery is total — the work happens whether or not anyone is watching', 'You competed with your past self as much as anyone in front of you', 'Your focus is your most defining quality — it is never casual'],
    shareCaption: `I paid $1.50 and my personality resonates with Kobe Bryant — The Mamba Mentality. Whose archetype are you? → yourone.world`, color: '#8020c8',
  },
  venus_williams: {
    id: 'venus_williams', name: 'Venus Williams', title: 'The Pioneer',
    tagline: 'You walked through every door that did not exist yet. Then you held it open.',
    description: `Your personality resonates with Venus Williams's archetype — the person who moved first and paid the cost that first-movers always pay, and did not complain about it. You fought for the conditions that made others possible. Your grace in that position is the result of enormous strength.`,
    why: ['You moved first — and paid the cost that first-movers always pay, without complaint', 'You fought for conditions that made others possible — the sacrifice was structural', 'Your grace under unfair conditions is the result of enormous and deliberate strength'],
    shareCaption: `I paid $1.50 and my personality resonates with Venus Williams — The Pioneer. Whose archetype are you? → yourone.world`, color: '#e88080',
  },
  lewis_hamilton: {
    id: 'lewis_hamilton', name: 'Lewis Hamilton', title: 'The Trailblazer',
    tagline: 'You won the game and then changed what the game was for.',
    description: `Your personality resonates with Lewis Hamilton's archetype — the person who achieved the highest level of excellence in a world that did not fully welcome them, and then used that platform for something larger. You refuse to be reduced to your sport.`,
    why: ['You achieved excellence in a space that did not fully welcome you — and then used the platform', 'You refuse to be reduced to one dimension — your identity is multiple and intentional', 'You changed what your position meant — not just won it'],
    shareCaption: `I paid $1.50 and my personality resonates with Lewis Hamilton — The Trailblazer. Whose archetype are you? → yourone.world`, color: '#9820e8',
  },
  naomi_osaka: {
    id: 'naomi_osaka', name: 'Naomi Osaka', title: 'The Quiet Storm',
    tagline: 'Your silence said more than anyone else\'s words.',
    description: `Your personality resonates with Naomi Osaka's archetype — the person who prioritised their mental health publicly, at enormous cost, and changed the conversation in doing so. Your power is not loud. It is clear. You hold your own counsel and act on it regardless of the pressure to do otherwise.`,
    why: ['You prioritised your mental health publicly and at real cost — changing the conversation', 'Your quiet is not weakness — it is a different frequency of power', 'You act on your own counsel regardless of external pressure — that is real authority'],
    shareCaption: `I paid $1.50 and my personality resonates with Naomi Osaka — The Quiet Storm. Whose archetype are you? → yourone.world`, color: '#c060d0',
  },
  stephen_curry: {
    id: 'stephen_curry', name: 'Stephen Curry', title: 'The Sharpshooter',
    tagline: 'You changed what was possible by refusing to accept what was standard.',
    description: `Your personality resonates with Stephen Curry's archetype — the person who was told they were too small and too slow and used that information to build a game nobody else could play. You are precise where others are powerful. You changed the standard so completely that the game itself reorganised around what you made possible.`,
    why: ['You refused the limits others assigned you — and built a game around that refusal', 'Your precision is your power — you are exact where others rely on force', 'You changed the standard so completely that the game reorganised around you'],
    shareCaption: `I paid $1.50 and my personality resonates with Stephen Curry — The Sharpshooter. Whose archetype are you? → yourone.world`, color: '#4060d8',
  },
  // ── History (10) ─────────────────────────────────────────────────────────────
  martin_luther_king: {
    id: 'martin_luther_king', name: 'Martin Luther King Jr.', title: 'The Dream Keeper',
    tagline: 'You held a vision of a world that did not exist. You made it more possible.',
    description: `Your personality resonates with Martin Luther King Jr.'s archetype — the person who held a vision so large and so specific that it rearranged what was possible in the minds of millions. Your courage was not the absence of fear — it was the decision to continue in the presence of it.`,
    why: ['You hold a vision larger than what currently exists — and you believe in it completely', 'Your courage is not fearlessness — it is continuing in the presence of fear because the vision matters more', 'Your words become the structure others navigate by — they outlast the moment they were spoken'],
    shareCaption: `I paid $1.50 and my personality resonates with Martin Luther King Jr. — The Dream Keeper. Whose archetype are you? → yourone.world`, color: '#4070c8',
  },
  mahatma_gandhi: {
    id: 'mahatma_gandhi', name: 'Mahatma Gandhi', title: 'The Peaceful Force',
    tagline: 'You understood that the method was the message. Always.',
    description: `Your personality resonates with Gandhi's archetype — the person who understood that how you fight is inseparable from what you are fighting for. You are more strategic than you appear. Your patience is not passive — it is the most advanced form of resistance available.`,
    why: ['You understand that method and message are inseparable — how you do it IS what you stand for', 'Your patience is strategic resistance — not passivity but the highest form of active opposition', 'You live the change you demand — that is not idealism, it is the only legitimate position'],
    shareCaption: `I paid $1.50 and my personality resonates with Mahatma Gandhi — The Peaceful Force. Whose archetype are you? → yourone.world`, color: '#e8b848',
  },
  malala_yousafzai: {
    id: 'malala_yousafzai', name: 'Malala Yousafzai', title: 'The Youngest Voice',
    tagline: 'They tried to silence you. It made you louder.',
    description: `Your personality resonates with Malala's archetype — the person who refused to be silenced by forces that understood the power of what she was saying. Your courage is not abstract. It is specific. You speak for the people who cannot yet enter the rooms you have earned access to.`,
    why: ['Your courage is not abstract — it is specific and it operates in the presence of real threat', 'You speak for those who cannot yet enter the rooms you have earned access to', 'Your voice grew louder in proportion to the pressure to silence it — that is not defiance, it is necessity'],
    shareCaption: `I paid $1.50 and my personality resonates with Malala Yousafzai — The Youngest Voice. Whose archetype are you? → yourone.world`, color: '#40b8a8',
  },
  frida_kahlo: {
    id: 'frida_kahlo', name: 'Frida Kahlo', title: 'The Pain Painter',
    tagline: 'You made your suffering into something beautiful enough to change how people see.',
    description: `Your personality resonates with Frida Kahlo's archetype — the person who turned the material of their suffering into art that outlasted them. You do not separate the personal from the political. Your body and your identity are the subject. Your honesty about pain is an act of resistance.`,
    why: ['You turn the material of your suffering into something that reaches others — the pain is the medium', 'You do not separate the personal from the political — they are the same territory', 'Your honesty about pain is resistance — you refuse to make it invisible'],
    shareCaption: `I paid $1.50 and my personality resonates with Frida Kahlo — The Pain Painter. Whose archetype are you? → yourone.world`, color: '#e84028',
  },
  andy_warhol: {
    id: 'andy_warhol', name: 'Andy Warhol', title: 'The Art Factory',
    tagline: 'You understood what was coming before everyone else. You made art about it.',
    description: `Your personality resonates with Andy Warhol's archetype — the person who saw the direction of culture before it arrived and made art that was already post-ironic about it. You understood celebrity, commerce, and image as subjects before anyone else was willing to say so. Your shyness and your spectacle were both completely real.`,
    why: ['You saw what was coming before anyone else — the culture caught up to your predictions decades later', 'You understood celebrity and commerce as art subjects before it was acceptable to say so', 'Your shyness and your spectacle were equally real — both were the person'],
    shareCaption: `I paid $1.50 and my personality resonates with Andy Warhol — The Art Factory. Whose archetype are you? → yourone.world`, color: '#d8d840',
  },
  marie_curie: {
    id: 'marie_curie', name: 'Marie Curie', title: 'The Scientific Pioneer',
    tagline: 'You worked in rooms not built for you and discovered things no one else had found.',
    description: `Your personality resonates with Marie Curie's archetype — the person who maintained intellectual rigour in conditions designed to exclude them, and produced discoveries that changed science twice. Your discipline came from love of the work, not from the desire for recognition.`,
    why: ['You worked in rooms not built for you — and produced discoveries that changed everything', 'Your discipline comes from love of the work, not from the desire for recognition', 'You discovered things nobody else was looking for because nobody else was looking that carefully'],
    shareCaption: `I paid $1.50 and my personality resonates with Marie Curie — The Scientific Pioneer. Whose archetype are you? → yourone.world`, color: '#80c8e8',
  },
  carl_sagan: {
    id: 'carl_sagan', name: 'Carl Sagan', title: 'The Cosmos Communicator',
    tagline: 'You made the vastness feel intimate. That took real love.',
    description: `Your personality resonates with Carl Sagan's archetype — the person who understood that wonder is not the enemy of rigour and spent their life proving it. You communicate complex things in ways that land with people who had no reason to care — and then they care. Your sense of cosmic perspective is not diminishing. It is clarifying.`,
    why: ['You communicate wonder and rigour simultaneously — you never made them enemies', 'You make the complex feel accessible without making it simple — that is the hardest thing', 'Your sense of cosmic scale is clarifying and ultimately generous — it puts things in their place'],
    shareCaption: `I paid $1.50 and my personality resonates with Carl Sagan — The Cosmos Communicator. Whose archetype are you? → yourone.world`, color: '#4868d8',
  },
  jane_goodall: {
    id: 'jane_goodall', name: 'Jane Goodall', title: 'The Patient Observer',
    tagline: 'You waited long enough to see what no one else had seen. The patience was the method.',
    description: `Your personality resonates with Jane Goodall's archetype — the person who understood that real attention is the rarest scientific instrument. You are more comfortable in close observation than in most institutions. Your advocacy comes from love, not from argument, and people feel the difference.`,
    why: ['Your patience is your primary method — you wait long enough to see what rushing would miss', 'You are more comfortable with close observation than with institution — that is precision, not unsociability', 'Your advocacy comes from love — and people feel the difference between that and argument'],
    shareCaption: `I paid $1.50 and my personality resonates with Jane Goodall — The Patient Observer. Whose archetype are you? → yourone.world`, color: '#40a830',
  },
  winston_churchill: {
    id: 'winston_churchill', name: 'Winston Churchill', title: 'The Defiant',
    tagline: 'You refused to accept the moment as permanent. That refusal saved things.',
    description: `Your personality resonates with Churchill's archetype — the person who holds a position under conditions that would break most people, not through absence of fear but through the refusal to let that fear become a public fact. Your rhetoric is a tool for collective courage.`,
    why: ['You hold positions under pressure that would break most people — the refusal is the act', 'Your words are tools for collective courage — you know how to make others feel what you need them to feel', 'You are more complex than any monument version of you — the contradictions are real'],
    shareCaption: `I paid $1.50 and my personality resonates with Winston Churchill — The Defiant. Whose archetype are you? → yourone.world`, color: '#808040',
  },
  cleopatra: {
    id: 'cleopatra', name: 'Cleopatra', title: 'The Last Pharaoh',
    tagline: 'You were the most powerful person in the room. You made sure they knew it differently each time.',
    description: `Your personality resonates with Cleopatra's archetype — the person who understood that power is performed as much as it is held, and who mastered both simultaneously. You could speak to everyone in their own language, literally and otherwise. Your intelligence was your most formidable weapon.`,
    why: ['You understood that power is performed — and you mastered the performance and the substance simultaneously', 'Your intelligence was your primary weapon — you spoke to everyone in their own language', 'You adapted completely to every environment while maintaining the core that never changed'],
    shareCaption: `I paid $1.50 and my personality resonates with Cleopatra — The Last Pharaoh. Whose archetype are you? → yourone.world`, color: '#c89820',
  },
  // ── Business (10) ────────────────────────────────────────────────────────────
  jeff_bezos: {
    id: 'jeff_bezos', name: 'Jeff Bezos', title: 'The Everything Builder',
    tagline: 'You took the long view when everyone else was looking at the quarter.',
    description: `Your personality resonates with Jeff Bezos's archetype — the person who operates on a time horizon that makes conventional business strategy look myopic. You are willing to lose money now to own the infrastructure later. Your ambition does not fit the normal category — it operates at the level of civilisation.`,
    why: ['You operate on a time horizon that makes conventional thinking look small', 'You invest in infrastructure others have not yet imagined needing — the patience is the strategy', 'Your ambition does not fit normal categories — it operates at a level of civilisation'],
    shareCaption: `I paid $1.50 and my personality resonates with Jeff Bezos — The Everything Builder. Whose archetype are you? → yourone.world`, color: '#f8a020',
  },
  bill_gates: {
    id: 'bill_gates', name: 'Bill Gates', title: 'The Software Architect',
    tagline: 'You saw the platform before anyone knew what a platform was.',
    description: `Your personality resonates with Bill Gates's archetype — the person who saw the structural layer that everyone else would eventually need to operate on, and positioned themselves there first. Your second act is run with the same systems thinking as the first. For you, the problem is always a systems problem.`,
    why: ['You see the structural layer others have not yet recognised they need', 'You think in systems — every problem is a systems problem to you', 'Your second chapter applies the same rigour as the first — the method does not change'],
    shareCaption: `I paid $1.50 and my personality resonates with Bill Gates — The Software Architect. Whose archetype are you? → yourone.world`, color: '#4888e8',
  },
  warren_buffett: {
    id: 'warren_buffett', name: 'Warren Buffett', title: 'The Patient Investor',
    tagline: 'You understood something simple that almost no one can actually do.',
    description: `Your personality resonates with Warren Buffett's archetype — the person who identified a principle early and had the discipline to hold it against every temptation to abandon it. Your wisdom is not complex — it is applied consistently over decades, which is far harder than complexity.`,
    why: ['You identified a principle early and held it for decades — consistency is the whole strategy', 'Your wisdom is not complex — it is applied consistently, which is harder than complexity', 'You understand people and incentives as well as numbers — that is the real source of your judgement'],
    shareCaption: `I paid $1.50 and my personality resonates with Warren Buffett — The Patient Investor. Whose archetype are you? → yourone.world`, color: '#c88030',
  },
  richard_branson: {
    id: 'richard_branson', name: 'Richard Branson', title: 'The Adventurer',
    tagline: 'You bet on yourself constantly. The scorecard is the life.',
    description: `Your personality resonates with Richard Branson's archetype — the person who decided that adventure and enterprise are not separate categories. You take risks at a scale that most people would consider reckless, and you take them with a genuine joy that is impossible to fake.`,
    why: ['You take risks at a scale others experience as reckless — your confidence is earned through the track record', 'You experience adventure and enterprise as the same activity — the distinction does not exist for you', 'Your joy in what you do is genuinely infectious — people want to follow you just to see what happens'],
    shareCaption: `I paid $1.50 and my personality resonates with Richard Branson — The Adventurer. Whose archetype are you? → yourone.world`, color: '#e83030',
  },
  mark_zuckerberg: {
    id: 'mark_zuckerberg', name: 'Mark Zuckerberg', title: 'The Connection Architect',
    tagline: 'You built the infrastructure for human connection. The consequences were larger than the intention.',
    description: `Your personality resonates with Mark Zuckerberg's archetype — the person who built something so structurally embedded in how people operate that the original vision is almost irrelevant compared to the reality. You are more curious about human behaviour than your public image suggests.`,
    why: ['You build infrastructure others live inside — the consequences operate beyond your original intent', 'You are more curious about human behaviour than your public image suggests', 'You are in the middle of understanding what you created — the story is not finished'],
    shareCaption: `I paid $1.50 and my personality resonates with Mark Zuckerberg — The Connection Architect. Whose archetype are you? → yourone.world`, color: '#2888e8',
  },
  sheryl_sandberg: {
    id: 'sheryl_sandberg', name: 'Sheryl Sandberg', title: 'The Lean Leader',
    tagline: 'You made a seat at the table and then showed others how to get there.',
    description: `Your personality resonates with Sheryl Sandberg's archetype — the person who understood that structural barriers require structural solutions. You built the argument for inclusion with the same precision you brought to everything else. Your vulnerability — when you chose it — was the book.`,
    why: ['You understand that structural barriers require structural solutions — not just individual effort', 'You made your own seat at the table and then described the process for others', 'Your vulnerability — when you chose it — was your most powerful and honest act'],
    shareCaption: `I paid $1.50 and my personality resonates with Sheryl Sandberg — The Lean Leader. Whose archetype are you? → yourone.world`, color: '#6848b8',
  },
  jk_rowling: {
    id: 'jk_rowling', name: 'J.K. Rowling', title: 'The World Builder',
    tagline: 'You built a world so complete it became real for millions of people.',
    description: `Your personality resonates with J.K. Rowling's archetype — the person who sat at a table with nothing and built an entire alternative reality, complete and internally consistent, that would eventually matter to more people than most countries. Your imagination is not escapism — it is architecture.`,
    why: ['You build complete worlds — internally consistent, fully inhabited, structurally real', 'Your imagination is architecture — the creativity is the method, not just the output', 'You think through the things that matter most by building worlds around them — that is not escape, it is inquiry'],
    shareCaption: `I paid $1.50 and my personality resonates with J.K. Rowling — The World Builder. Whose archetype are you? → yourone.world`, color: '#9028d0',
  },
  alan_turing: {
    id: 'alan_turing', name: 'Alan Turing', title: 'The Computing Pioneer',
    tagline: 'You built the foundation for the world nobody could yet see coming.',
    description: `Your personality resonates with Alan Turing's archetype — the person who asked the right question before the question was even comprehensible to the people around them. You think in abstractions that turn out to be the most practical things ever invented. You continued because the question was the thing.`,
    why: ['You asked questions not yet comprehensible to those around you — and answered them anyway', 'Your abstractions turn out to be the most practical things ever invented — theory is practice at your level', 'You continued in isolation because the question was the thing — that is pure and rare'],
    shareCaption: `I paid $1.50 and my personality resonates with Alan Turing — The Computing Pioneer. Whose archetype are you? → yourone.world`, color: '#40a8d8',
  },
  jack_ma: {
    id: 'jack_ma', name: 'Jack Ma', title: 'The Persistence Story',
    tagline: 'Every no made you more sure you were asking the right question.',
    description: `Your personality resonates with Jack Ma's archetype — the person who was rejected so completely and so often that the pattern itself became proof of something important. Your persistence is not stubbornness — it is a deep conviction that what you are building is necessary.`,
    why: ['Your persistence is a deep conviction that what you are building is necessary — not stubbornness', 'Every rejection became fuel — you converted opposition into motivation structurally', 'You understood the market before the market understood itself — that is the only real advantage'],
    shareCaption: `I paid $1.50 and my personality resonates with Jack Ma — The Persistence Story. Whose archetype are you? → yourone.world`, color: '#e87020',
  },
  ray_dalio: {
    id: 'ray_dalio', name: 'Ray Dalio', title: 'The Principle Builder',
    tagline: 'You turned your mistakes into a system. Then you shared the system.',
    description: `Your personality resonates with Ray Dalio's archetype — the person who is not afraid of being wrong because they have a method for being wrong productively. You build systems for everything — including the system by which you discover you are wrong. Your transparency is a tool as much as a value.`,
    why: ['You build systems for everything — including for being wrong productively', 'Your transparency is a tool — you have found it structurally useful, not just morally correct', 'You learn from every mistake at a level of rigour others do not apply — that is the source of the edge'],
    shareCaption: `I paid $1.50 and my personality resonates with Ray Dalio — The Principle Builder. Whose archetype are you? → yourone.world`, color: '#286888',
  },
}
